### ISSUE TITLE
Binary does not have an execute permission by default

### ISSUE THREAD

**Issue by ZIMkaRU** [develar/app-builder#97]
After update from `4.1.0` to `4.2.0` I faced `Permission denied`
Looks like binaries do not have an execute permission by default
after `fs.chmodSync(appBuilderPath, '755')` or `sudo chmod +x` it works as expected

---

Logs:

```console
/bin/sh: 1: /project/node_modules/app-builder-bin/linux/x64/app-builder: Permission denied
Error in updating YAML file and configurations with blockmap Error: Command failed: /project/node_modules/app-builder-bin/linux/x64/app-builder blockmap --input=/project/dist/BitfinexReport-4.17.0-beta.0-x64-mac.zip --output=/project/dist/BitfinexReport-4.17.0-beta.0-x64-mac.zip.blockmap --compression=gzip
/bin/sh: 1: /project/node_modules/app-builder-bin/linux/x64/app-builder: Permission denied

    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at Object.<anonymous> (/project/scripts/node/generate-mac-zipand-blockmap.js:37:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at afterAllArtifactBuild (/project/electron-builder-config.js:252:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /project/node_modules/app-builder-lib/src/index.ts:81:36
    at executeFinally (/project/node_modules/builder-util/src/promise.ts:12:14) {
  status: 126,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 2f 62 69 6e 2f 73 68 3a 20 31 3a 20 2f 70 72 6f 6a 65 63 74 2f 6e 6f 64 65 5f 6d 6f 64 75 6c 65 73 2f 61 70 70 2d 62 75 69 6c 64 65 72 2d 62 69 6e 2f ... 41 more bytes>
  ],
  pid: 1382,
  stdout: <Buffer >,
  stderr: <Buffer 2f 62 69 6e 2f 73 68 3a 20 31 3a 20 2f 70 72 6f 6a 65 63 74 2f 6e 6f 64 65 5f 6d 6f 64 75 6c 65 73 2f 61 70 70 2d 62 75 69 6c 64 65 72 2d 62 69 6e 2f ... 41 more bytes>
}

```

**Comment by mmaietta** [comment]
I'm actually still trying to fix this. It seems that the executable permissions get removed on upload? I added this to the build script and the executable still didn't keep the permission set
https://github.com/develar/app-builder/blob/b431059964d10ca794e0f9c73b983854605abe16/scripts/build.sh#L43

**Comment by mmaietta** [comment]
Fixed in https://github.com/develar/app-builder/releases/tag/v5.0.0-alpha.1

pnpm requires `publishConfig.executableFiles: [<files>]` in the package.json to keep the +x permissions

**Comment by ZIMkaRU** [comment]
@mmaietta thanks
